
[INFO ] 2018-04-18 11:03:03 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:03:03 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:03:03 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:03:03 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 11:03:04 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 11:04:06 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:04:06 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:04:06 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:04:06 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:04:37 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:04:37 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:04:37 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:04:37 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:09:43 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:09:43 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:09:43 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:09:43 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:10:40 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:10:40 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:10:40 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:10:40 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:11:25 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:11:25 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:11:25 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:11:25 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 11:11:25 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 11:14:35 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:14:35 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:14:35 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:14:35 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 11:14:35 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 11:15:34 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:15:34 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:15:34 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 11:15:34 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 11:15:34 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:02:22 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:02:22 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:02:22 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:02:22 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 19:02:23 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:10:32 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:10:32 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:10:32 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:10:32 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 19:10:32 ErrorHandler - 1 : 64 - cvc-elt.1: Cannot find the declaration of element 'Product'.
[INFO ] 2018-04-18 19:15:59 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:15:59 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:15:59 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:15:59 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 19:15:59 ErrorHandler - 1 : 64 - cvc-elt.1: Cannot find the declaration of element 'Product'.
[INFO ] 2018-04-18 19:28:59 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:28:59 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:28:59 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:28:59 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 19:28:59 ErrorHandler - 1 : 141 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:34:01 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:34:01 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:34:01 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:34:01 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 19:34:01 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:40:30 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:40:30 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:40:30 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:40:30 ProductDao - Result Set of adding 1
[WARN ] 2018-04-18 19:40:30 ErrorHandler - 1 : 229-SchemaLocation: schemaLocation value = 'CategoryC:\Users\Michael\MavensProjectsCources\lesson9\src\main\resources\xml\category.xsd' must have even number of URI's.
[ERROR] 2018-04-18 19:40:30 ErrorHandler - 1 : 229 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:41:33 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:41:33 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:41:33 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:41:33 ProductDao - Result Set of adding 1
[WARN ] 2018-04-18 19:41:33 ErrorHandler - 1 : 221-SchemaLocation: schemaLocation value = 'C:\Users\Michael\MavensProjectsCources\lesson9\src\main\resources\xml\category.xsd' must have even number of URI's.
[ERROR] 2018-04-18 19:41:33 ErrorHandler - 1 : 221 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:45:39 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:45:39 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:45:39 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:45:39 ProductDao - Result Set of adding 1
[WARN ] 2018-04-18 19:45:39 ErrorHandler - 1 : 233-SchemaLocation: schemaLocation value = 'C:\Users\Michael\MavensProjectsCources\lesson9\src\main\resources\xml\category.xsd' must have even number of URI's.
[ERROR] 2018-04-18 19:45:39 ErrorHandler - 1 : 233 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:48:09 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:48:09 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:48:09 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:48:09 ProductDao - Result Set of adding 1
[WARN ] 2018-04-18 19:48:09 ErrorHandler - 1 : 223-SchemaLocation: schemaLocation value = 'C:\Users\Michael\MavensProjectsCources\lesson9\src\main\resources\xml\category.xsd' must have even number of URI's.
[ERROR] 2018-04-18 19:48:09 ErrorHandler - 1 : 223 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 19:51:01 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:51:01 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:51:01 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 19:51:01 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 19:51:01 ErrorHandler - 1 : 232 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 22:01:52 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:01:52 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:01:52 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:01:52 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 22:01:52 ErrorHandler - 1 : 232 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 22:05:37 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:05:37 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:05:37 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:05:37 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 22:05:37 ErrorHandler - 1 : 232 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 22:06:10 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:06:10 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:06:11 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 22:06:11 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 22:06:11 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-18 23:07:11 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 23:07:11 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 23:07:11 ProductDao - Result Set of adding 1
[INFO ] 2018-04-18 23:07:11 ProductDao - Result Set of adding 1
[ERROR] 2018-04-18 23:07:12 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-25 17:59:19 ProductDao - Result Set of adding 1
[INFO ] 2018-04-25 17:59:19 ProductDao - Result Set of adding 1
[INFO ] 2018-04-25 17:59:19 ProductDao - Result Set of adding 1
[INFO ] 2018-04-25 17:59:19 ProductDao - Result Set of adding 1
[ERROR] 2018-04-25 17:59:19 ProductDao - Error
java.sql.SQLException: Column 'c.name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1093) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5488) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategory(ProductDao.java:118) [classes/:?]
	at persistence.Run.main(Run.java:25) [classes/:?]
[ERROR] 2018-04-25 17:59:19 ProductDao - Error
java.sql.SQLException: Column 'c.name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1093) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5488) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:142) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 17:59:20 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[INFO ] 2018-04-25 18:02:16 ProductDao - Result Set of adding 1
[INFO ] 2018-04-25 18:02:16 ProductDao - Result Set of adding 1
[INFO ] 2018-04-25 18:02:16 ProductDao - Result Set of adding 1
[INFO ] 2018-04-25 18:02:16 ProductDao - Result Set of adding 1
[ERROR] 2018-04-25 18:02:16 ProductDao - Error
java.sql.SQLException: Column 'c.name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1093) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5488) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategory(ProductDao.java:118) [classes/:?]
	at persistence.Run.main(Run.java:25) [classes/:?]
[ERROR] 2018-04-25 18:02:16 ProductDao - Error
java.sql.SQLException: Column 'c.name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1093) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5488) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:142) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:02:16 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:02:59 ProductDao - Error
[ERROR] 2018-04-25 18:02:59 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'products'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46) ~[mysql-connector-java-5.1.6.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:422) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:137) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ConnectionPool.getConnection(ConnectionPool.java:9) ~[classes/:?]
	at persistence.dao.ProductDao.showProductsWithCategory(ProductDao.java:107) [classes/:?]
	at persistence.Run.main(Run.java:25) [classes/:?]
[ERROR] 2018-04-25 18:02:59 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'products'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46) ~[mysql-connector-java-5.1.6.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:422) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:137) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ConnectionPool.getConnection(ConnectionPool.java:9) ~[classes/:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:135) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:02:59 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:03:09 ProductDao - Error
[ERROR] 2018-04-25 18:03:09 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'products'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46) ~[mysql-connector-java-5.1.6.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:422) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:137) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ConnectionPool.getConnection(ConnectionPool.java:9) ~[classes/:?]
	at persistence.dao.ProductDao.showProductsWithCategory(ProductDao.java:107) [classes/:?]
	at persistence.Run.main(Run.java:25) [classes/:?]
[ERROR] 2018-04-25 18:03:09 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'products'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46) ~[mysql-connector-java-5.1.6.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:422) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:137) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ConnectionPool.getConnection(ConnectionPool.java:9) ~[classes/:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:135) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:03:09 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:04:50 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:05:42 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:06:18 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:09:08 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:20) [classes/:?]
[ERROR] 2018-04-25 18:09:08 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:21) [classes/:?]
[ERROR] 2018-04-25 18:09:08 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:22) [classes/:?]
[ERROR] 2018-04-25 18:09:08 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:23) [classes/:?]
[ERROR] 2018-04-25 18:09:08 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:09:16 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:20) [classes/:?]
[ERROR] 2018-04-25 18:09:16 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:21) [classes/:?]
[ERROR] 2018-04-25 18:09:16 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:22) [classes/:?]
[ERROR] 2018-04-25 18:09:16 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:23) [classes/:?]
[ERROR] 2018-04-25 18:09:16 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:10:20 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:20) [classes/:?]
[ERROR] 2018-04-25 18:10:20 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:21) [classes/:?]
[ERROR] 2018-04-25 18:10:20 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:22) [classes/:?]
[ERROR] 2018-04-25 18:10:20 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:23) [classes/:?]
[ERROR] 2018-04-25 18:10:20 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:14:24 ProductDao - Error
java.sql.SQLException: Field 'id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:33) [classes/:?]
	at persistence.Run.main(Run.java:20) [classes/:?]
[ERROR] 2018-04-25 18:14:24 ProductDao - Error
java.sql.SQLException: Field 'id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:33) [classes/:?]
	at persistence.Run.main(Run.java:21) [classes/:?]
[ERROR] 2018-04-25 18:14:24 ProductDao - Error
java.sql.SQLException: Field 'id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:33) [classes/:?]
	at persistence.Run.main(Run.java:22) [classes/:?]
[ERROR] 2018-04-25 18:14:24 ProductDao - Error
java.sql.SQLException: Field 'id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:33) [classes/:?]
	at persistence.Run.main(Run.java:23) [classes/:?]
[ERROR] 2018-04-25 18:14:24 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:19:11 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:20) [classes/:?]
[ERROR] 2018-04-25 18:19:11 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:21) [classes/:?]
[ERROR] 2018-04-25 18:19:11 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:22) [classes/:?]
[ERROR] 2018-04-25 18:19:11 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`products`.`product`, CONSTRAINT `FK_product` FOREIGN KEY (`id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:23) [classes/:?]
[ERROR] 2018-04-25 18:19:11 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:27:53 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:29:10 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:29:10 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:34:43 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:34:43 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:35:26 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:35:26 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:35:33 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:35:33 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:36:48 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:36:48 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:38:39 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:38:39 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:41:17 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:41:17 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:49:19 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:49:19 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:50:00 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:50:01 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:50:31 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:50:31 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:50:48 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:50:48 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:54:39 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:54:39 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:58:30 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:58:31 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 18:59:06 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 18:59:06 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:02:05 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 19:02:05 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:09:12 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:120) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 19:09:12 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:09:40 ProductDao - Error
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3288) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3272) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4108) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:121) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 19:09:40 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:10:16 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:12:30 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:13:45 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:14:04 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'category_id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:20) [classes/:?]
[ERROR] 2018-04-25 19:14:04 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'category_id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:21) [classes/:?]
[ERROR] 2018-04-25 19:14:04 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'category_id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:22) [classes/:?]
[ERROR] 2018-04-25 19:14:04 ProductDao - Error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'category_id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.addProduct(ProductDao.java:34) [classes/:?]
	at persistence.Run.main(Run.java:23) [classes/:?]
[ERROR] 2018-04-25 19:14:04 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:14:46 ProductDao - Error
[ERROR] 2018-04-25 19:14:46 ProductDao - Error
java.sql.SQLException: Column 'product_id' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1093) ~[mysql-connector-java-5.1.6.jar:?]
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2734) ~[mysql-connector-java-5.1.6.jar:?]
	at persistence.dao.ProductDao.showProductsWithCategoryByCategoryName(ProductDao.java:128) [classes/:?]
	at persistence.Run.main(Run.java:26) [classes/:?]
[ERROR] 2018-04-25 19:14:46 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:15:21 ProductDao - Error
[ERROR] 2018-04-25 19:15:21 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:16:09 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:16:19 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:18:32 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:18:36 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:20:47 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:24:22 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 19:59:23 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 20:00:02 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
[ERROR] 2018-04-25 20:00:06 ErrorHandler - 1 : 65 - cvc-elt.1: Cannot find the declaration of element 'Category'.
